apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skopeo-cache
  namespace: ai-voice-assistant
  labels:
    app: skopeo-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
